name: deploy-scripts
env:
  DOMAIN_NAME: "client.boykos.ru"
  USER_NAME: "ubuntu"
  REPO_NAME: "client.boykos"
  
on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.newpariskey }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
        
      - name: RSYNC to DOMAIN
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --ignore-errors --archive /home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/* ${{ env.USER_NAME }}@15.237.135.74:/var/www/client.boykos/
